version: '3.9'

services:
  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql/data
